# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_deliveries', models.IntegerField(default=1)),
                ('total_earnings', models.FloatField()),
                ('total_tips', models.IntegerField(default=0)),
                ('total_tip_amount', models.FloatField()),
            ],
        ),
    ]
