# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('service', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('wait_time', models.FloatField()),
                ('distance', models.FloatField()),
                ('num_dropoffs', models.IntegerField(default=1)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
        ),
    ]
