# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='num_dropoffs',
        ),
        migrations.AddField(
            model_name='delivery',
            name='base_earning',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='time_accepted',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='tip',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
